apiVersion: v1
kind: Service
metadata:
  labels:
    # 用于给 endpoint 实现标签绑定
    app: lb-exporter
  name: lb-exporter
  namespace: test-vm
spec:
  selector:
    app: lb-exporter
  ports:
  - name: metrics
    protocol: TCP
    port: 9120
    targetPort: 9120
